### PR TITLE
Bug Fixes & Dependency Injection Improvements

### LINKED ISSUE #406: Null Pointer exceptions in Version 5.13.5
Null Pointer exceptions in Version 5.13.5

https://hastebin.com/osociyiyit.php

### PR DESCRIPTION
**Pull request by egg82**
* Added better .gitignore
* Fixed static Main/Plugin access with Service Locator pattern
* Changed User to VoteUser to avoid hiding/shadowing
* Fixed NPE in VoteSite#broadcastVote (Fixes #406 )
* Fixed minor bugs caught by SpotBugs plugin

### CODE REVIEW

**Comment by BenCodez** [comment]
I don't want to change the user object to VoteUser. Would require other plugins that use my api to update, don't want to do that atm. Gonna just post an update for a quick bug fix. Wanna post these as seperate pr's?

**Comment by egg82** [comment]
Could add a "User" interface that points to VoteUser instead- the change is for your benefit, so you don't confuse the two on accident. At least using an interface will notify you with colors.

**Comment by BenCodez** [comment]
I've never confused them :P

**Comment by egg82** [comment]
True enough- I suppose when I say "your" benefit I mean the benefit of anyone writing code for it. Most people will use automatic imports and/or may select the wrong "User" object which may have unintended consequences. Finding this sort of bug is made harder with imports being at the top so you don't see the issue right away. By avoiding shadowing you avoid this issue altogether, though as you stated this is part of your API which can't be removed. By at least moving to an interface it's much easier to tell what's the API and what's the underlying User object in your base library.

**Comment by BenCodez** [comment]
Maybe in a future version

**Comment by egg82** [comment]
alrighty, everything looks good on my end here. Fixed the API and the merge conflict.

**Comment by BenCodez** [comment]
I'll look more at it later, got other stuff atm I need to worry about :P

**Comment by BenCodez** [comment]
I also don't really wanna use the service lib. Prefer it to be the way it is currently.

**Comment by egg82** [comment]
Fair enough. Your current solution is to pass the Plugin object by reference AND use a static "Plugin" object in the Main class as well as other classes. While passing-by-reference can be fine in most cases, the statics are what I worry about most. It creates a large dependency chain and will normally end in spaghetti code. Even passing-by-reference can be difficult to update if you decide things need to be moved.

**Comment by BenCodez** [comment]
I'll save the changing about the static plugin object in a later release, I'll merge the other changes though.

**Comment by BenCodez** [comment]
Closing this for now, will look at in the future.

**Pull request closed without merging**
