### PR TITLE
added option "DisableLineBreaking" to prevent that items are corruped

### PR DESCRIPTION
**Pull request by Wolf2323**
Our item, that is given to the player is a little bit more complex. We check with other plugins, if the item equals a specific item. The line breaking of the lore, beak this compare. In reason of that, i added a option, to siable this line beaking.

I am sure, there are other options to solve this problem, but i prefere this. It would be nice, to have this solution in the plugin, to solve this problem.

### CODE REVIEW

**Comment by BenCodez** [comment]
There is an option already, but a global option, I'm thinking of disabling the lore breaks with items given from rewards though

**Comment by Wolf2323** [comment]
what is this global option, i couldn't find it

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

    checkLoreLength = data.getBoolean("CheckLoreLength", true);
    loreLength = data.getInt("LoreLength", -1);

Default option in Config: (Not in config by default)

    NewLoreLength: 30

**Comment by Wolf2323** [comment]
thanks for the fast solution/fix, i now use `CheckLoreLength: false` and this works fine ;)
I close this now

**Pull request closed without merging**
