### PR TITLE
Add an "sqlProperties" key that allows for additional SQL arguments to be passed

### PR DESCRIPTION
**Pull request by dominicfeliton**
Title.

Config excerpt:

#sqlProperties: ''
#EX: 'useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true'

Some of these arguments are required for databases like mine; otherwise, SQL will refuse to establish a connection.

### CODE REVIEW

**Comment by BenCodez** [comment]
This is already possible under Line: '&whatever you need to add' under MySQL, both bungee and spigot servers.

**Comment by dominicfeliton** [comment]
Yikes, thanks so much! Apologies, closing

**Comment by dominicfeliton** [comment]
Sorry, I searched for that text in both configs, but I couldn't find anything. I don't mean to use this as a help thread but which entry in particular is it? Thank you so much

**Comment by BenCodez** [comment]
Just add it. It's not in the default config.

**Pull request closed without merging**
